#!/usr/bin/perl
use strict;
use warnings;
use 5.010;
use DateTime::Format::Strptime;
use Person;

my $date_parser = DateTime::Format::Strptime->new(
    pattern => '%Y-%m-%d',
);

my $dob = $date_parser->parse_datetime('1962-09-07');

my $dave = Person->new(
    name   => 'Dave',
    dob    => $dob,
    gender => 'M'
);

say $dave->dob->day_name;
